pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('restful-booker-karate/karate-api') {
                    sh 'docker build -t karate-api-tests .'
                }
            }
        }

        stage('Run Karate Tests') {
            steps {
                dir('restful-booker-karate/karate-api') {
                    sh '''
                      docker run --rm \
                        -v $PWD/target:/app/target \
                        karate-api-tests
                    '''
                }
            }
        }
    }

    post {
        always {
            publishHTML([
                allowMissing: false,
                alwaysLinkToLastBuild: true,
                keepAll: true,
                reportDir: 'restful-booker-karate/karate-api/target/karate-reports',
                reportFiles: 'karate-summary.html',
                reportName: 'Karate API Test Report'
            ])
        }
    }
}
